//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Launcher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Launcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button1link.
        /// </summary>
        internal static string ConfigButton1Link {
            get {
                return ResourceManager.GetString("ConfigButton1Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button1name.
        /// </summary>
        internal static string ConfigButton1Name {
            get {
                return ResourceManager.GetString("ConfigButton1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button2link.
        /// </summary>
        internal static string ConfigButton2Link {
            get {
                return ResourceManager.GetString("ConfigButton2Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button2name.
        /// </summary>
        internal static string ConfigButton2Name {
            get {
                return ResourceManager.GetString("ConfigButton2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button3link.
        /// </summary>
        internal static string ConfigButton3Link {
            get {
                return ResourceManager.GetString("ConfigButton3Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button3name.
        /// </summary>
        internal static string ConfigButton3Name {
            get {
                return ResourceManager.GetString("ConfigButton3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button4link.
        /// </summary>
        internal static string ConfigButton4Link {
            get {
                return ResourceManager.GetString("ConfigButton4Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button4name.
        /// </summary>
        internal static string ConfigButton4Name {
            get {
                return ResourceManager.GetString("ConfigButton4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button5link.
        /// </summary>
        internal static string ConfigButton5Link {
            get {
                return ResourceManager.GetString("ConfigButton5Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button5name.
        /// </summary>
        internal static string ConfigButton5Name {
            get {
                return ResourceManager.GetString("ConfigButton5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientip.
        /// </summary>
        internal static string ConfigClientIp {
            get {
                return ResourceManager.GetString("ConfigClientIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientname.
        /// </summary>
        internal static string ConfigClientName {
            get {
                return ResourceManager.GetString("ConfigClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clientversion.
        /// </summary>
        internal static string ConfigClientVersion {
            get {
                return ResourceManager.GetString("ConfigClientVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileserver.
        /// </summary>
        internal static string ConfigFileServer {
            get {
                return ResourceManager.GetString("ConfigFileServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launcherconfig.
        /// </summary>
        internal static string ConfigLauncherConfig {
            get {
                return ResourceManager.GetString("ConfigLauncherConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launchername.
        /// </summary>
        internal static string ConfigLauncherName {
            get {
                return ResourceManager.GetString("ConfigLauncherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launcherpatchserver.
        /// </summary>
        internal static string ConfigLauncherPatchServer {
            get {
                return ResourceManager.GetString("ConfigLauncherPatchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launcherupdatername.
        /// </summary>
        internal static string ConfigLauncherUpdaterName {
            get {
                return ResourceManager.GetString("ConfigLauncherUpdaterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to launcherversion.
        /// </summary>
        internal static string ConfigLauncherVersion {
            get {
                return ResourceManager.GetString("ConfigLauncherVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patchnotes.
        /// </summary>
        internal static string ConfigPatchNotes {
            get {
                return ResourceManager.GetString("ConfigPatchNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to patchserver.
        /// </summary>
        internal static string ConfigPatchServer {
            get {
                return ResourceManager.GetString("ConfigPatchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 001: No configuration file found, default file created..
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 010: Failed to retrieve patch notes. Invalid patch notes link. Please report this to an admin..
        /// </summary>
        internal static string Error10 {
            get {
                return ResourceManager.GetString("Error10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 011: Invalid launcher patch link..
        /// </summary>
        internal static string Error11 {
            get {
                return ResourceManager.GetString("Error11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 012: Failed confirming file integrity. Please reinstall your client..
        /// </summary>
        internal static string Error12 {
            get {
                return ResourceManager.GetString("Error12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 013: Failed to parse launcher config file. Please report this to an admin..
        /// </summary>
        internal static string Error13 {
            get {
                return ResourceManager.GetString("Error13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 014: Failed to connect to launcher server..
        /// </summary>
        internal static string Error14 {
            get {
                return ResourceManager.GetString("Error14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 015: Failed connecting to launcher server. Please report this error to an admin..
        /// </summary>
        internal static string Error15 {
            get {
                return ResourceManager.GetString("Error15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 016: Failed trying to download patch, invalid patch link. Please report this to an admin..
        /// </summary>
        internal static string Error16 {
            get {
                return ResourceManager.GetString("Error16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 017: Failed to locate launcher updater..
        /// </summary>
        internal static string Error17 {
            get {
                return ResourceManager.GetString("Error17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 018: Error extracting patch file..
        /// </summary>
        internal static string Error18 {
            get {
                return ResourceManager.GetString("Error18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 019: Failed connecting to launcher server. Please check your internet connection..
        /// </summary>
        internal static string Error19 {
            get {
                return ResourceManager.GetString("Error19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 002: Failed reading configuration file. Please report this error to an admin..
        /// </summary>
        internal static string Error2 {
            get {
                return ResourceManager.GetString("Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 003: Failed to locate client file..
        /// </summary>
        internal static string Error3 {
            get {
                return ResourceManager.GetString("Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 004: Invalid patch link..
        /// </summary>
        internal static string Error4 {
            get {
                return ResourceManager.GetString("Error4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 005: Failed to connect to patch server..
        /// </summary>
        internal static string Error5 {
            get {
                return ResourceManager.GetString("Error5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 006: Failed connecting to patch server. Please report this error to an admin..
        /// </summary>
        internal static string Error6 {
            get {
                return ResourceManager.GetString("Error6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 007: Failed to parse patch list file..
        /// </summary>
        internal static string Error7 {
            get {
                return ResourceManager.GetString("Error7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 008: Failed to parse patch version. Check patch list file! Please report this to an admin..
        /// </summary>
        internal static string Error8 {
            get {
                return ResourceManager.GetString("Error8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 009: Too many patch files to parse!.
        /// </summary>
        internal static string Error9 {
            get {
                return ResourceManager.GetString("Error9", resourceCulture);
            }
        }
    }
}
